# Site settings
title: HowToCoder
header-img: img/home-bg.jpg
email: thisispremsingh@gmail.com
copyright_name: Prem Singh
description: "Premprakash Singh | Software Developer from Mumbai, India!"
baseurl: "/"
url: "http://howtocoder.com"
twitter_username: premp_singh
github_username:  HowToCoder
facebook_username:  howtocoder
email_username:  thisispremsingh@gmail.com
insta_username: HowToCoder

# Author settings
author: Premprakash Singh
author-pic: profile.jpg
about-author: I’m a Software Developer from Mumbai, India. I am a learner who loves to code and learning new things. A freecodecamper, member of Chingu cohort as well (Bearded Dragon June cohort & Chingu-voyage cohort) and a newbie in open source development.

# Contact links
email: # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: artemsheludko # Add your Github handle
twitter: '@artemsheludko_' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# disqus comments configuration
disqus:
  shortname: premsingh
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-110019410-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title
paginate: 4
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
